CREATE DATABASE COMPUTER

USE COMPUTER

--Таблица с реализаторами

CREATE TABLE DISTRIBUTOR
(
	ID				INT PRIMARY KEY IDENTITY (0,1),
	[NAME]			NVARCHAR(MAX) NOT NULL,
	[ADDRESS]		NVARCHAR(MAX) NOT NULL,
	[PHONE]			NVARCHAR(MAX) NOT NULL
)
GO

--Таблица характеристик компьютера

CREATE TABLE SPECIFICATIONS
(
	[MANUFACTURERID] INT IDENTITY (0,1),
	[MODEL]			 NVARCHAR(MAX) NOT NULL,
	[CPU]			 NVARCHAR(MAX) NOT NULL,
	[FREQUENCY]		 INT		   NOT NULL,
	[RAM]			 INT		   NOT NULL,
	[HardDiskSpace]  INT		   NOT NULL,
	[RELEASEdATE]	 DATETIME	   NOT NULL,
	CONSTRAINT PC_MANUFACTURER PRIMARY KEY ([MANUFACTURERID])
)
GO

--Таблица с  поставками

CREATE TABLE CONSIGNMENT
(
	[IDCONSIGMENT]	 INT IDENTITY (0,1),
	[BATCHSIZE]		 INT NOT NULL,
	[PRICE]			 INT NOT NULL,
	CONSTRAINT PK_CONSIGMENT PRIMARY KEY ([IDCONSIGMENT])
)
GO

--Таблица с производителями

CREATE TABLE MANUFACTURER
(
	[IDMANUFACTURER]	INT IDENTITY (0,1), 
	[NAME]				NVARCHAR(MAX) NOT NULL,
	[ADDRESS]			NVARCHAR(MAX) NOT NULL,
	[SPECIFICATIONSID]	INT CONSTRAINT FK_MANUFACTURER_SPECIFICATIONS FOREIGN KEY REFERENCES SPECIFICATIONS ([MANUFACTURERID]),
	[CONSIGMENTID]		INT CONSTRAINT FK_MANUFACTURER_CONSIGMENT	  FOREIGN KEY REFERENCES CONSIGNMENT    ([IDCONSIGMENT]),
	CONSTRAINT PK_MANUFACTUR PRIMARY KEY  ([IDMANUFACTURER])
)
GO
drop table MANUFACTURER, CONSIGNMENT, SPECIFICATIONS, DISTRIBUTOR
